# Dockerfile for the generating the Archelon SFTP Docker image
#
# To build:
#
# docker build -t docker.lib.umd.edu/archelon-sftp:<VERSION> -f Dockerfile.sftp .
#
# where <VERSION> is the Docker image version to create.
FROM quay.io/panubo/sshd:1.10.0

# Adds configuration to allow the plastron user to SFTP files in and out of Archelon's
# "dropbox" using public keys stored in the Archelon Rails database.
RUN echo "AuthorizedKeysCommand /etc/archelon/get-plastron-authorized-keys.sh" >>/etc/ssh/sshd_config
RUN echo "AuthorizedKeysCommandUser nobody" >>/etc/ssh/sshd_config

# Install curl, as it is needed by the "get-plastron-authorized-keys.sh" script
RUN apk add curl

# Create the import and export directories and make them owned by the plastron user
RUN mkdir -p /data/imports && mkdir -p /data/exports
RUN chown 2200:2200 /data/*

# Run the panubo startup script to initialize the user and other configuration,
# so it gets baked into the image, and we can mount as much of this as possible
# as read-only filesystems at container runtime.
ENV SFTP_MODE=true
ENV SSH_USERS=plastron:2200:2200
RUN /entry.sh true

# This is the script that fetches the public keys of Archelon users over HTTP.
# It is intend to be used as the AuthorizedKeysCommand in the sshd_config.
# NOTE: On Kubernetes, we currently have to remount a new copy of this script
# to get the permissions correct; however, this Docker image should work as-is
# for local deployment via docker compose or docker stack.
COPY docker_config/archelon-sftp/get-plastron-authorized-keys.sh /etc/archelon/get-plastron-authorized-keys.sh
RUN chmod 755 /etc/archelon/get-plastron-authorized-keys.sh

# Override the panubo image's endpoint to always start the sshd daemon (the upstream
# image has a custom "/entrypoint" script that allows specifiying user(s) to create
# or an alternate command to run; we do not need that complexity.)
ENTRYPOINT ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config"]
