@startuml MessageFlow
skinparam Linetype ortho
<style>
Title {
    Margin 30
    FontSize 30
}
</style>
title
    Archelon ↔ Plastron
    Asynchonous Job Information Flow
end title

component Archelon {
    component ImportJobsForm
    component ImportJobsController {
        rectangle import << Method >>
        rectangle status_update << Method >>
    }
    component ImportJobsChannel
}
component ActiveMQ {
    queue "/queue/plastron.jobs" as Jobs
    queue "/queue/plastron.jobs.status" as JobStatus
    component PlastronJobsStatusRoute <<Camel Route>>
}
component "Plastron STOMP Daemon" as Plastron {
    rectangle CommandListener
    rectangle MessageProcessor
    rectangle AsynchronousResponseHandler
}

ImportJobsForm ..> import : job id
import ....>  Jobs : STOMP message
Jobs ...> CommandListener : command message
JobStatus <.. MessageProcessor : progress message
JobStatus <.. AsynchronousResponseHandler : status message

CommandListener ...> MessageProcessor : command
MessageProcessor ...> AsynchronousResponseHandler : processing result

PlastronJobsStatusRoute <... JobStatus : status message
status_update <.... PlastronJobsStatusRoute : status message
ImportJobsChannel <... status_update : job status
ImportJobsForm <... ImportJobsChannel : job status

@enduml
